### ISSUE TITLE
tf.gather_nd issue

### ISSUE THREAD

**Issue by gihyunkim** [taekwan-lee/adacos-tensorflow#1]
tf.gather_nd에서 TypeError: Tensors in list passed to 'values' of 'Pack' Op have types [int32, float32] that don't all match. 이러한 에러가 발생하는데요. 혹시 one_hot과 label을 input으로 받아올 때 어떻게 받아오시는지 알 수 있을까요

**Comment by gihyunkim** [comment]
해결했습니다~ 감사합니다~

**Comment by taekwan-lee** [comment]
I guess casting the type of `one_hot` to float32 would solve the problem.
